### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by samanpa** [RustPython/Parser#67]
Is there a plan to periodically publish updates of this crate to crates.io? Will like to use it externally without depending on git. 

If this is not planned please feel free to close this issue.

**Comment by youknowone** [comment]
Though the API is very unstable and quickly being changed, I want to publish parser related crates to crates.io.
Could you share which APIs do you use? It will be helpful to freeze APIs with priority.

**Comment by DimitrisJim** [comment]
> Could you share which APIs do you use? It will be helpful to freeze APIs with priority.

yeah, this discussion should also be made with other people who use the parser. Probably an RFC would be good to come to a consensus.

**Comment by mtshiba** [comment]
If your reason for hesitating to publish this crate is that it is unstable and you want people to use the stable version as much as possible, you can publish a "nightly version" as follows:

```toml
[package]
name = "mtshiba-dummycrate-1"
version = "0.0.0-unstable.0" # The `unstable` part can be any other string. For example, alpha, beta, nightly, etc.
edition = "2021"
description = "A dummy crate for testing"
license = "MIT"

[dependencies]
```

https://stackoverflow.com/questions/46373028/how-to-release-a-beta-version-of-a-crate-for-limited-public-testing

You cannot install this crate with `cargo install mtshiba-dummycrate-1`, but you can install it by specifying the version explicitly like `cargo install mtshiba-dummycrate-1@0.0.0-unstable.0`. The same applies to adding dependencies to Cargo.toml.

Even if several versions have already been released, unstable versions cannot be used unless explicitly specified.

(If there is some other reason why a new version cannot be released right now, please ignore it.)
